# Default properties values
info.build:
  name: test
  description: the test for jpa by lfwang

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  output.ansi.enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-test?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
logging.level:
  com.tianjian: DEBUG